version: '3.5'

# #############################################################
# ##### Networks
# #############################################################
networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge

# #############################################################
# ##### Anchors
# #############################################################
x-service-php: &service-php
  build:
    context: .
    target: target_product_php
  healthcheck:
    interval: 10s
    timeout: 3s
    retries: 3
    start_period: 30s
  networks:
    - frontend
    - backend
  restart: always

x-service-php-product: &service-php-product
  <<: *service-php
  env_file: .env

x-service-nginx: &service-nginx
  build:
    context: .
    target: target_product_nginx
  restart: always
  networks:
    - frontend

x-service-nginx-proxy: &service-nginx-proxy
  image: nginxproxy/nginx-proxy:alpine
  restart: always
  networks:
    - frontend

# #############################################################
# ##### Services
# #############################################################
services:
  product-php:
    container_name: product-php
    <<: *service-php-product
    volumes:
      - ./:/srv/app:rw,cached

  product-nginx:
    container_name: product-nginx
    <<: *service-nginx
    depends_on:
      - product-php
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./public:/srv/app/public:ro
    environment:
      - VIRTUAL_HOST=${HOST_NAME:?HOST_NAME is not set or empty}

  product-nginx-proxy:
    container_name: product-nginx-proxy
    <<: *service-nginx-proxy
    ports:
      - target: 80
        published: 8001
        protocol: tcp
    volumes:
      - ./docker/nginx-proxy/certs:/etc/nginx/certs:ro
      - ./docker/nginx-proxy/vhost.d:/etc/nginx/vhost.d:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro

  ## Supervisor for consumers and retries
  supervisord:
    <<: *service-php-product
    volumes:
      - ./:/srv/app:rw,cached
    container_name: product-supervisord
    command: ["/usr/bin/supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf"]
    networks:
      - backend

  ## RabbitMQ
  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    container_name: product-rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER:-admin}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS:-admin}
    ports:
      # The standard AMQP protocol port
      - target: 5672
        published: 5672
      # HTTP management UI
      - target: 15672
        published: 15672
    networks:
      - backend

  mysql:
    platform: linux/x86_64
    image: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=about-you-task
      - MYSQL_USER=about-you
      - MYSQL_PASSWORD=about-you
    volumes:
      - ./docker/mysql/data:/var/lib/mysql'
    networks:
      - backend
