App\Entity\Order:
  attributes:
    id:
      groups: ['order', 'customer']
    grandTotal:
      groups: ['order', 'customer']
    store:
      groups: ['order', 'customer']
    status:
      groups: ['order', 'customer']
    scheduledPickupDate:
      groups: ['order', 'customer', 'station']
    scheduledReturnDate:
      groups: ['order', 'customer', 'station']
    returnedDate:
      groups: ['order', 'customer', 'station']
    createdAt:
      groups: ['order', 'customer']
    updatedAt:
      groups: ['order', 'customer']
    items:
      groups: ['order', 'station']
    pickupStation:
      groups: ['order']
    returnStation:
      groups: ['order']
    customer:
      groups: ['order']      