App\Entity\OrderItem:
  attributes:
    id:
      groups: ['order_item', 'order', 'station']
    quantity:
      groups: ['order_item', 'order', 'station']
    name:
      groups: ['order_item', 'order', 'station']
    price:
      groups: ['order_item', 'order']
    paymentMethod:
      groups: ['order_item', 'order']
    createdAt:
      groups: ['order_item', 'order']
    order:
      groups: ['order_item']
    product:
      groups: ['order_item', 'order']
