App\Entity\Product:
  attributes:
    id:
      groups: ['product', 'offer', 'order']
    slug:
      groups: ['product', 'offer', 'order']
    name:
      groups: ['product', 'offer', 'order', 'order_item']
    shortDescription:
      groups: ['product', 'offer', 'order']
    description:
      groups: ['product', 'offer', 'order']
    price:
      groups: ['product', 'offer', 'order']
    createdAt:
      groups: ['product', 'offer']
    updatedAt:
      groups: ['product', 'offer']
    categories:
      groups: ['product']
    stations:
      groups: ['product']
